DROP TABLE IF EXISTS arch_db.wra_covid_screening;
CREATE TABLE IF NOT EXISTS arch_db.wra_covid_screening
(
    record_id                  INTEGER     NOT NULL PRIMARY KEY,
    redcap_event_name          VARCHAR(32) NOT NULL,
    redcap_repeat_instrument   VARCHAR(32) NOT NULL,
    redcap_repeat_instance     SMALLINT    NOT NULL,
    hh_scrn_num_obsloc         VARCHAR(14) NOT NULL,
    hhe_hh_member_id           SMALLINT NOT NULL,
    scrn_obsstdat              DATE NOT NULL,
    wra_enr_interviewer_obsloc MEDIUMTEXT NOT NULL,
    wra_ptid                   VARCHAR(6) NULL,
    c19vax_cmyn                SMALLINT,
    c19vax_cmtrt               SMALLINT,
    covid_scrn_3               SMALLINT,
    c19_lbperf                 SMALLINT,
    covid_test_dt_range        MEDIUMTEXT,
    c19_lbdat                  DATE,
    c19_lborres                SMALLINT,
    fever_ceoccur              SMALLINT,
    cough_ceoccur              SMALLINT,
    shortbreath_ceoccur        SMALLINT,
    sorethroat_ceoccur         SMALLINT,
    fatigue_ceoccur            SMALLINT,
    myalgia_ceoccur            SMALLINT,
    anorexia_ceoccur           SMALLINT,
    nausea_ceoccur             SMALLINT,
    diarrhoea_ceoccur          SMALLINT,
    ageusia_ceoccur            SMALLINT,
    anosmia_ceoccur            SMALLINT,
    runnynose_ceoccur          SMALLINT,
    sneeze_ceoccur             SMALLINT,
    headache_ceoccur           SMALLINT,
    rash_ceoccur               SMALLINT,
    conjunct_ceoccur           SMALLINT,
    cs_is_referral_required    SMALLINT,
    c19_contact_dx_ceoccur     SMALLINT,
    c19_contact_sx_ceoccur     SMALLINT,
    covid_scrn_9               SMALLINT,
    c19_zm_scorres             SMALLINT,
    covid_scrn_comments_yn     BIT,
    covid_scrn_comments        TEXT
);
CREATE UNIQUE INDEX wra_ptid_idx ON arch_db.wra_covid_screening (wra_ptid);
CREATE INDEX hh_scrn_num_obsloc_idx ON arch_db.wra_covid_screening (hh_scrn_num_obsloc);
