DROP TABLE IF EXISTS arch_db.wra_enrollment;
CREATE TABLE IF NOT EXISTS arch_db.wra_enrollment
(
    id                           int auto_increment primary key,
    wra_enrollment_id            bigint unsigned,
    record_id                    int                                   not null,
    redcap_event_name            mediumtext                            not null,
    redcap_repeat_instrument     mediumtext                            not null,
    redcap_repeat_instance       int(1)                                not null,
    hh_scrn_num_obsloc           varchar(14)                           not null,
    wra_enr_visit_count          int                                   null,
    hhe_hh_member_id             int                                   null,
    scrn_obsstdat                date                                  not null,
    wra_enr_interviewer_obsloc   TINYTEXT                              not null,
    wra_timestamp                TIMESTAMP                             null,
    wra_enr_hhh_pvc              smallint                              not null,
    wra_enr_reas_decline         mediumtext                            null,
    wra_enr_pp_avail             smallint                              null,
    estimated_age                int                                   null,
    wra_enr_nok_avail            bit                                   null,
    kin_lang_scorres             TINYINT                               null,
    kin_lang_scorres_oth         TINYTEXT                              null,
    con_witness_signature_pryn   bit                                   null,
    icf_nok_ca1                  bit                                   null,
    icf_nok_ca2                  bit                                   null,
    icf_nok_ca3                  bit                                   null,
    icf_nok_ca4                  bit                                   null,
    icf_nok_ca5                  bit                                   null,
    icf_nok_ca6                  bit                                   null,
    icf_nok_score                int                                   null,
    wra_enr_nok_signature        mediumtext                            null,
    con_lar_signdat              date                                  null,
    wra_enr_nok_name             TINYTEXT                              null,
    wra_enr_nok_ra_signature     mediumtext                            null,
    con_lar_signdat_2            date                                  null,
    wra_enr_nok_ra_name          mediumtext                            null,
    con_lar_yn_dsdecod           bit                                   null,
    wra_enr_nok_ltsa             bit                                   null,
    wra_enr_nok_lts_signature    mediumtext                            null,
    wra_enr_nok_lts_sign_date    date                                  null,
    wra_enr_nok_lts_name         TINYTEXT                              null,
    wra_enr_nok_name_ent         smallint                              null,
    wra_enr_nok_lts_ra_sign      mediumtext                            null,
    wra_enr_nok_lts_ra_sign_date date                                  null,
    wra_enr_nok_lts_ra_name      TINYTEXT                              null,
    wra_enr_witness_sign         mediumtext                            null,
    con_witness_signdat          date                                  null,
    wra_enr_witness_name         TINYTEXT                              null,
    wra_enr_part_lang            smallint                              null,
    part_lang_other              mediumtext                            null,
    wra_enr_wrdc                 bit                                   null,
    icf_ca1                      bit                                   null,
    icf_ca2                      bit                                   null,
    icf_ca3                      bit                                   null,
    icf_ca4                      bit                                   null,
    icf_ca5                      bit                                   null,
    icf_ca6                      bit                                   null,
    icf_score                    smallint                              null,
    wra_enr_aasp                 bit                                   null,
    catchment_ieorres            bit                                   null,
    wra_enr_part_signature       mediumtext                            null,
    con_dsstdat                  date                                  null,
    wra_participant_name         TINYTEXT                              null,
    con_yn_dsdecod               bit                                   null,
    wra_enr_ra_signature         mediumtext                            null,
    wra_enr_ra_sign_date         date                                  null,
    wra_ra_name                  mediumtext                            null,
    con_samples_dsdecod          bit                                   null,
    wra_enr_part_sign_lts        mediumtext                            null,
    wra_enr_date_lts             date                                  null,
    wra_enr_part_name_lts        mediumtext                            null,
    wra_enr_lts_ra_signature     mediumtext                            null,
    wra_enr_lts_ra_sign_date     date                                  null,
    wra_lts_ra_name              TINYTEXT                              null,
    wra_enr_sign_wit             mediumtext                            null,
    wra_enr_sign_date_wit        date                                  null,
    wra_enr_pr_wit_name          TINYTEXT                              null,
    wra_enr_pdrv                 date                                  null,
    wra_enr_ptrv                 tinyint                               null,
    othr_reason_ieorres_1        bit                                   null,
    othr_reason_ieorres_2        bit                                   null,
    othr_reason_ieorres_3        bit                                   null,
    othr_reason_ieorres_4        bit                                   null,
    othr_reason_ieorres_5        bit                                   null,
    othr_reason_ieorres_6        bit                                   null,
    othr_spfy_ieorres            TINYTEXT                              null,
    wra_zenrol_flag              bit                                   null,
    icc_eligibility_adult_1      bit                                   null,
    icc_eligibility_minor_1      bit                                   null,
    icc_ineligibility_1          bit                                   null,
    icc_icc_signed_1             bit                                   null,
    icc_ica_not_signed_1         bit                                   null,
    icc_ica_sign_time            time                                  null,
    icc_wra_or_nok_read          bit                                   null,
    icc_lang                     TINYTEXT                              null,
    icc_witness_name             TINYTEXT                              null,
    icc_witness_rel              TINYTEXT                              null,
    icc_per_sop                  bit                                   null,
    icc_check1                   bit                                   null,
    icc_check2                   bit                                   null,
    icc_check3                   bit                                   null,
    icc_check4                   bit                                   null,
    icc_accepted_sign            int                                   null,
    icc_ra_signature             text                                  null,
    icc_sign_date                date                                  null,
    icc_comments                 mediumtext                            null,
    brthdat                      date                                  null,
    wra_age                      smallint                              null,
    wra_ptid                     varchar(6)                            null,
    fname_scorres                mediumtext                            null,
    mname_scorres                mediumtext                            null,
    lname_scorres                mediumtext                            null,
    oname_scorres                mediumtext                            null,
    wra_enr_comments_yn          bit                                   null,
    wra_enr_comments             text                                  null,
    is_wra_enrolled              bit                                   null,
    hfs_coyn                     bit                                   null,
    is_forms_completed           bit                                   null,
    wra_forms_complete           tinyint,
    created_at                   timestamp default current_timestamp() not null,
    created_by                   varchar(36)                           null,
    updated_at                   timestamp                             null on update current_timestamp(),
    updated_by                   varchar(36)                           null
);

CREATE INDEX enr_wra_ptid_idx ON arch_db.wra_enrollment (wra_ptid);
CREATE INDEX enr_hh_scrn_num_obsloc_idx ON arch_db.wra_enrollment (hh_scrn_num_obsloc);
CREATE INDEX enr_wra_enrollment_id_idx ON arch_db.wra_enrollment (wra_enrollment_id);
CREATE INDEX enr_record_id_idx ON arch_db.wra_enrollment (record_id);

