DROP TABLE IF EXISTS arch_db.wra_fu_pregnany_assessment;
CREATE TABLE arch_db.wra_fu_pregnany_assessment
(
    record_id                          BIGINT     NOT NULL PRIMARY KEY,
    redcap_event_name                  VARCHAR(18) NOT NULL,
    redcap_repeat_instrument           VARCHAR(24) NOT NULL,
    redcap_repeat_instance             VARCHAR(30),
    pa_visit_date                      DATE,
    wra_pregnancy_id                   VARCHAR(14),
    np_zapps_scorres                   SMALLINT,
    np_zapps_ptid                      VARCHAR(11),
    np_zapps_id_src                    SMALLINT,
    np_ident_arch                      BIT,
    np_ptw_1                           BIT         NOT NULL,
    np_ptw_2                           BIT         NOT NULL,
    np_ptw_3                           BIT         NOT NULL,
    np_ptw_4                           BIT         NOT NULL,
    np_ptw_5                           BIT         NOT NULL,
    np_ptw_6                           BIT         NOT NULL,
    np_ptw_7                           BIT         NOT NULL,
    np_anc_mhyn                        BIT,
    np_anc_num_mh                      INTEGER,
    np_anc1_dat                        DATE,
    np_anc1_ga                         INTEGER,
    anc1_ga_weeks                      INTEGER,
    anc1_ga_months                     INTEGER,
    np_anc_plan_obsloc                 BIT,
    birth_plan_fac_obsloc              INTEGER,
    facility_other                     INTEGER,
    birth_other_loc                    VARCHAR(69),
    np_del_decide_scorres              INTEGER,
    del_decide_spfy_scorres            VARCHAR(74),
    cph_comments_yn                    BIT,
    cph_comments                       VARCHAR(107),
    np_alc_suyn                        BIT,
    np_alc_cons                        INTEGER,
    np_tob_suyn                        BIT,
    np_tob_cur_sudosfrq                INTEGER,
    tob_oth_sutrt_1                    BIT         NOT NULL,
    tob_oth_sutrt_2                    BIT         NOT NULL,
    tob_oth_sutrt_3                    BIT         NOT NULL,
    tob_oth_sutrt_4                    BIT         NOT NULL,
    tob_oth_sutrt_5                    BIT         NOT NULL,
    tob_oth_sutrt_6                    BIT         NOT NULL,
    tob_oth_sutrt_7                    BIT         NOT NULL,
    other_tbc_use                      VARCHAR(30),
    np_drug_suyn                       BIT,
    np_drug_usage                      VARCHAR(30),
    np_drug_sutrt_1                    BIT         NOT NULL,
    np_drug_sutrt_2                    BIT         NOT NULL,
    np_drug_sutrt_3                    BIT         NOT NULL,
    np_drug_sutrt_4                    BIT         NOT NULL,
    np_drug_sutrt_5                    BIT         NOT NULL,
    np_drug_sutrt_6                    BIT         NOT NULL,
    np_drug_sutrt_7                    BIT         NOT NULL,
    np_drug_sutrt_othr                 VARCHAR(30),
    hbp_comments_yn                    BIT,
    hbp_comments                       VARCHAR(69),
    zr_visit_date                      DATE,
    name_veri                          SMALLINT,
    brthdat_veri                       SMALLINT,
    ref_likely_scorres                 SMALLINT,
    ref_res_decline_1                  BIT         NOT NULL,
    ref_res_decline_2                  BIT         NOT NULL,
    ref_res_decline_3                  BIT         NOT NULL,
    ref_res_decline_4                  BIT         NOT NULL,
    ref_res_decline_5                  BIT         NOT NULL,
    ref_res_decline_6                  BIT         NOT NULL,
    zr_2_other                         MEDIUMTEXT,
    pref_zapps_scorres                 INTEGER,
    apnt_dat_scorres                   DATE,
    zr_confirm_contact                 BIT,
    preg_test                          VARCHAR(25),
    zr_ega_days                        INTEGER,
    zr_wra_ptid                        VARCHAR(6),
    zr_comm_yn                         BIT,
    zr_comm                            MEDIUMTEXT,
    wra_pregnancy_assessments_complete INTEGER     NOT NULL
);
