DROP TABLE IF EXISTS arch_db.wra_mental_health_assessment;
CREATE TABLE IF NOT EXISTS arch_db.wra_mental_health_assessment
(
    record_id                             BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    redcap_event_name                     VARCHAR(32)     NOT NULL,
    redcap_repeat_instrument              VARCHAR(32)     NOT NULL,
    redcap_repeat_instance                SMALLINT,
    mh_visit_date                         DATE,
    phq9_interest_scorres                 TINYINT,
    phq9_dprs_scorres                     TINYINT,
    phq9_sleep_scorres                    TINYINT,
    phq9_tired_scorres                    TINYINT,
    phq9_app_scorres                      TINYINT,
    phq9_bad_scorres                      TINYINT,
    phq9_conc_scorres                     TINYINT,
    phq9_slow_scorres                     TINYINT,
    phq9_hurt_scorres                     TINYINT,
    phq9_difficult_scorres                TINYINT,
    phq9_total_scorres                    TINYINT,
    zds_depression_sevr                   VARCHAR(32),
    ds_is_cr_required                     TINYINT,
    phq9_coyn                             BIT,
    phq9_coval                            TINYTEXT,
    anx_interviewer_obsloc                VARCHAR(32),
    anx_visit_date                        DATE,
    anx_1                                 TINYINT,
    anx_2                                 TINYINT,
    anx_3                                 TINYINT,
    anx_4                                 TINYINT,
    anx_5                                 TINYINT,
    anx_6                                 TINYINT,
    anx_7                                 TINYINT,
    anx_total_score                       SMALLINT,
    gad_result                            VARCHAR(32),
    anx_comments_yn                       BIT,
    anx_comments                          TINYTEXT,
    pss_upset_scorres                     TINYINT,
    pss_no_ctrl_scorres                   TINYINT,
    pss_nervous_scorres                   TINYINT,
    pss_confid_scorres                    TINYINT,
    pss_yrway_scorres                     TINYINT,
    pss_cope_scorres                      TINYINT,
    pss_ctrl_scorres                      TINYINT,
    pss_ontop_scorres                     TINYINT,
    pss_anger_scorres                     TINYINT,
    pss_dfclt_scorres                     TINYINT,
    pss_total_scorres                     TINYINT,
    sa_zassessment_result                 VARCHAR(32),
    pss_coyn                              BIT,
    ss_comments                           TINYTEXT,
    wra_mental_health_assessment_complete SMALLINT
);
CREATE INDEX mha_anx_interviewer_obsloc_idx ON arch_db.wra_mental_health_assessment (anx_interviewer_obsloc);
