DROP TABLE IF EXISTS arch_db.wra_preg_overview_surveillance;
CREATE TABLE IF NOT EXISTS arch_db.wra_preg_overview_surveillance
(
    record_id                                        BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    redcap_event_name                                VARCHAR(32)     NOT NULL,
    redcap_repeat_instrument                         VARCHAR(64)     NOT NULL,
    redcap_repeat_instance                           TINYINT,
    pos_visit_date                                   DATE,
    ph_prev_rporres                                  TINYINT,
    pho_num_preg_rporres                             TINYINT,
    ph_live_rporres                                  TINYINT,
    pho_preg_count                                   TINYINT,
    ph_loss_rporres                                  TINYINT,
    ph_bs_rporres_2                                  TINYINT,
    ph_bs_rporres                                    TINYINT,
    pho_loss_count                                   TINYINT,
    stlb_num_rporres_2                               TINYINT,
    stlb_num_rporres                                 TINYINT,
    pho_comments_yn                                  BIT,
    pho_comments                                     MEDIUMTEXT,
    lmp_reg_scorres                                  TINYINT,
    lmp_kd_scorres                                   TINYINT,
    lmp_kd_scorres_other                             TINYTEXT,
    lmp_start_scorres                                SMALLINT,
    lmp_scdat                                        DATE,
    lmp_cat_scorres                                  SMALLINT,
    lmp_start_weeks                                  SMALLINT,
    lmp_start_months                                 SMALLINT,
    lmp_start_years                                  SMALLINT,
    lmp_scorres                                      TINYINT,
    ps_mens_cal_yn                                   TINYINT,
    lmp_dt_rec_cal                                   TINYINT,
    preg_scorres                                     SMALLINT,
    months_preg_scorres                              SMALLINT,
    np_pregid_mhyn                                   SMALLINT,
    np_date_of_test                                  VARCHAR(10),
    np_date_of_test_2                                VARCHAR(10),
    np_us_test_dat                                   VARCHAR(10),
    np_bld_test_dat                                  VARCHAR(10),
    apreg_date                                       VARCHAR(7),
    ps_pregnancy_id                                  VARCHAR(14),
    np_us_edd_dat                                    DATE,
    np_edd_src                                       TINYINT,
    preg_surv_comm                                   BIT,
    preg_surv_commnts                                MEDIUMTEXT,
    wra_pregnancy_overview_and_surveillance_complete SMALLINT        NOT NULL
);
