-- DROP TABLE IF EXISTS map_and_list;
CREATE TABLE map_and_list
(
    id         INT            NOT NULL AUTO_INCREMENT,
    FID        INTEGER        NOT NULL,
    FID_1      INTEGER        NOT NULL,
    zone       INTEGER        NOT NULL,
    cluster    INTEGER        NOT NULL,
    sbn        INTEGER        NOT NULL,
    hun        VARCHAR(3),
    hhn        VARCHAR(2),
    screenid   VARCHAR(14),
    gps_obtain BIT            NOT NULL,
    latitude   VARCHAR(10),
    longitude  VARCHAR(9),
    neighbourh VARCHAR(37),
    address    VARCHAR(107),
    st_type    INTEGER,
    specify_ot VARCHAR(6),
    Location   VARCHAR(1),
    Latitude_1 NUMERIC(10, 6),
    Longitud_1 NUMERIC(9, 6),
    occupancy  INTEGER,
    occupied_v VARCHAR(1),
    can_gather VARCHAR(1),
    hh_name    VARCHAR(28),
    hh_total_m VARCHAR(2),
    hh_wra     VARCHAR(1),
    hh_c2      VARCHAR(1),
    record_not VARCHAR(1),
    notes      VARCHAR(160),
    Isthereano BIT,
    Istherea_1 BIT,
    _merge     VARCHAR(15)    NOT NULL,
    st_sticker VARCHAR(1),
    displayhhs VARCHAR(1),
    displayuni VARCHAR(1),
    FID_2      INTEGER        NOT NULL,
    FID_1_1    INTEGER        NOT NULL,
    FID_1_1_1  INTEGER        NOT NULL,
    OBJECTID   BIT            NOT NULL,
    GEOID      INTEGER,
    GEOID2     BIT            NOT NULL,
    WARD_N     VARCHAR(7),
    DIST_N     VARCHAR(6),
    PROV_N     VARCHAR(6),
    CONST_N    VARCHAR(7),
    HH         INTEGER        NOT NULL,
    POP        INTEGER        NOT NULL,
    REG        INTEGER        NOT NULL,
    CSA        INTEGER        NOT NULL,
    SEA        INTEGER        NOT NULL,
    CLUSTER_1  INTEGER        NOT NULL,
    FID_2_1    INTEGER        NOT NULL,
    SHAPE_Leng NUMERIC(11, 9) NOT NULL,
    SHAPE_Area NUMERIC(11, 9) NOT NULL,
    FID_3      INTEGER        NOT NULL,
    CSA_1      INTEGER        NOT NULL,
    Ward       VARCHAR(7),
    Ward_Code  BIT            NOT NULL,
    Zone_N     INTEGER        NOT NULL,
    PRIMARY KEY (id),
    INDEX (id, zone, cluster, sbn, hun, hhn)
);
