/**
 * WRA ZAPPS Referred Participants Tracker.
 *
 * @author Gift Jr <muyembegift@gmail.com> | 07.04.25
 * @since 0.0.3
 * @alias WRA ZAPPS Referrals
 */
CREATE OR REPLACE ALGORITHM = MERGE VIEW vw_wra_zapps_referrals
AS
SELECT *
FROM (SELECT pa_v1.record_id,
             pa_v1.screening_id,
             pa_v1.visit_date,
             pa_v1.visit_number,
             pa_v1.ra                                 as refferring_staff,
             pa_v1.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v1.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v1.upt_result,
             pa_v1.pregnancy_id,
             pa_v1.lmp_date,
             pa_v1.first_positive_upt_date,
             pa_v1.ega_by_lmp,
             pa_v1.edd_by_ega,
             pa_v1.zapps_referral_outcome,
             pa_v1.zapps_referral_declined_reasons,
             IF(pa_v1.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v1.wra_ptid, REPLACE(pa_v1.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v1.preferred_zapps_clinic,
             pa_v1.preferred_zapps_appointment_date
      FROM crt_wra_visit_1_pregnancy_assessments_overview pa_v1
               LEFT JOIN crt_wra_visit_1_locator_overview loc ON pa_v1.record_id = loc.record_id
      UNION
      SELECT pa_v2.record_id,
             pa_v2.screening_id,
             pa_v2.visit_date,
             pa_v2.visit_number,
             pa_v2.ra                                 as refferring_staff,
             pa_v2.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v2.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v2.upt_result,
             pa_v2.pregnancy_id,
             pa_v2.lmp_date,
             pa_v2.first_positive_upt_date,
             pa_v2.ega_by_lmp,
             pa_v2.edd_by_ega,
             pa_v2.zapps_referral_outcome,
             pa_v2.zapps_referral_declined_reasons,
             IF(pa_v2.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v2.wra_ptid, REPLACE(pa_v2.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v2.preferred_zapps_clinic,
             pa_v2.preferred_zapps_appointment_date
      FROM crt_wra_visit_2_pregnancy_assessments_overview pa_v2
               LEFT JOIN crt_wra_visit_2_locator_overview loc ON pa_v2.record_id = loc.record_id
      UNION
      SELECT pa_v3.record_id,
             pa_v3.screening_id,
             pa_v3.visit_date,
             pa_v3.visit_number,
             pa_v3.ra                                 as refferring_staff,
             pa_v3.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v3.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v3.upt_result,
             pa_v3.pregnancy_id,
             pa_v3.lmp_date,
             pa_v3.first_positive_upt_date,
             pa_v3.ega_by_lmp,
             pa_v3.edd_by_ega,
             pa_v3.zapps_referral_outcome,
             pa_v3.zapps_referral_declined_reasons,
             IF(pa_v3.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v3.wra_ptid, REPLACE(pa_v3.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v3.preferred_zapps_clinic,
             pa_v3.preferred_zapps_appointment_date
      FROM crt_wra_visit_3_pregnancy_assessments_overview pa_v3
               LEFT JOIN crt_wra_visit_3_locator_overview loc ON pa_v3.record_id = loc.record_id
      UNION
      SELECT pa_v4.record_id,
             pa_v4.screening_id,
             pa_v4.visit_date,
             pa_v4.visit_number,
             pa_v4.ra                                 as refferring_staff,
             pa_v4.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v4.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v4.upt_result,
             pa_v4.pregnancy_id,
             pa_v4.lmp_date,
             pa_v4.first_positive_upt_date,
             pa_v4.ega_by_lmp,
             pa_v4.edd_by_ega,
             pa_v4.zapps_referral_outcome,
             pa_v4.zapps_referral_declined_reasons,
             IF(pa_v4.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v4.wra_ptid, REPLACE(pa_v4.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v4.preferred_zapps_clinic,
             pa_v4.preferred_zapps_appointment_date
      FROM crt_wra_visit_4_pregnancy_assessments_overview pa_v4
               LEFT JOIN crt_wra_visit_4_locator_overview loc ON pa_v4.record_id = loc.record_id
      UNION
      SELECT pa_v5.record_id,
             pa_v5.screening_id,
             pa_v5.visit_date,
             pa_v5.visit_number,
             pa_v5.ra                                 as refferring_staff,
             pa_v5.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v5.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v5.upt_result,
             pa_v5.pregnancy_id,
             pa_v5.lmp_date,
             pa_v5.first_positive_upt_date,
             pa_v5.ega_by_lmp,
             pa_v5.edd_by_ega,
             pa_v5.zapps_referral_outcome,
             pa_v5.zapps_referral_declined_reasons,
             IF(pa_v5.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v5.wra_ptid, REPLACE(pa_v5.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v5.preferred_zapps_clinic,
             pa_v5.preferred_zapps_appointment_date
      FROM crt_wra_visit_5_pregnancy_assessments_overview pa_v5
               LEFT JOIN crt_wra_visit_5_locator_overview loc ON pa_v5.record_id = loc.record_id
      UNION
      SELECT pa_v6.record_id,
             pa_v6.screening_id,
             pa_v6.visit_date,
             pa_v6.visit_number,
             pa_v6.ra                                 as refferring_staff,
             pa_v6.wra_ptid,
             get_WRA_FullName(loc.alternate_id)       as wra_name,
             pa_v6.age,
             loc.first_contact_number,
             loc.first_contact_number_owner,
             loc.first_contact_person_identification  as first_contact_number_caller_id,
             loc.second_contact_number,
             loc.second_contact_number_owner,
             loc.second_contact_person_identification as second_contact_number_caller_id,
             pa_v6.upt_result,
             pa_v6.pregnancy_id,
             pa_v6.lmp_date,
             pa_v6.first_positive_upt_date,
             pa_v6.ega_by_lmp,
             pa_v6.edd_by_ega,
             pa_v6.zapps_referral_outcome,
             pa_v6.zapps_referral_declined_reasons,
             IF(pa_v6.zapps_referral_outcome = 'Accepted',
                CONCAT_WS('-', pa_v6.wra_ptid, REPLACE(pa_v6.preferred_zapps_appointment_date, '-', '/')),
                '')                                   as arch_zapps_id,
             pa_v6.preferred_zapps_clinic,
             pa_v6.preferred_zapps_appointment_date
      FROM crt_wra_visit_5_pregnancy_assessments_overview pa_v6
               LEFT JOIN crt_wra_visit_6_locator_overview loc ON pa_v6.record_id = loc.record_id) z
ORDER BY z.visit_date DESC;

