CREATE TABLE IF NOT EXISTS arch_db.hh_enumeration
(
    hhe_id                         bigint                                not null
        primary key,
    record_id                      int                                   not null,
    redcap_event_name              tinytext                              not null,
    redcap_repeat_instrument       tinytext                              null,
    redcap_repeat_instance         int                                   null,
    hh_scrn_num_obsloc             varchar(14)                           not null,
    hhe_interviewer                tinytext                              not null,
    hhe_interview_date             date                                  not null,
    hhe_member_count               tinyint                               null,
    hhe_member_eligibility         tinytext                              null,
    hhe_eligibe_wra_flag           tinytext                              null,
    hhe_sex_txt                    tinytext                              null,
    ahhe_f_count_total             int                                   null,
    hhe_hh_member_id               int                                   null,
    fname_scorres                  tinytext                              not null,
    mname_scorres                  tinytext                              null,
    lname_scorres                  tinytext                              not null,
    hh_rel_scorres                 tinyint                               null,
    sex                            tinyint                               null,
    hhe_p_live_here                bit                                   null,
    age_scorres                    int                                   not null,
    marital_scorres                tinyint                               null,
    hhe_part_available             tinyint                               not null,
    hhe_hh_count                   tinyint                               null,
    female_count                   tinyint                               null,
    m_count_remainder              tinyint                               null,
    male_count                     tinyint                               null,
    hhe_female_count               tinyint                               null,
    household_enumeration_complete tinyint                               not null,
    migration_status               tinyint                               not null,
    created_at                     timestamp default current_timestamp() not null,
    created_by                     tinytext                              null,
    updated_at                     timestamp default current_timestamp() not null on update current_timestamp(),
    updated_by                     tinytext                              null
);
