DROP TABLE IF EXISTS arch_db.hh_fu_enumeration;
CREATE TABLE IF NOT EXISTS arch_db.hh_fu_enumeration
(
    hhe_fu_id                         BIGINT                                NOT NULL PRIMARY KEY,
    record_id                         INTEGER                               NOT NULL,
    redcap_event_name                 VARCHAR(36)                           NOT NULL,
    redcap_repeat_instrument          VARCHAR(36)                           NOT NULL,
    redcap_repeat_instance            SMALLINT                              NOT NULL,
    fu_hh_scrn                        VARCHAR(30),
    fu_hhe_interviewer                VARCHAR(36)                           NOT NULL,
    fu_hhe_interview_date             DATE                                  NOT NULL,
    fu_hhe_member_count               SMALLINT                              NOT NULL,
    fu_hhe_member_eligibility         VARCHAR(16)                           NOT NULL,
    fu_hhe_eligibe_wra_flag           VARCHAR(16),
    fu_hhe_sex_txt                    VARCHAR(8)                            NOT NULL,
    fu_ahhe_f_count_total             SMALLINT,
    fu_hhe_hh_member_id               SMALLINT                              NOT NULL,
    fu_fname_scorres                  VARCHAR(32)                           NOT NULL,
    fu_mname_scorres                  VARCHAR(32),
    fu_lname_scorres                  VARCHAR(32)                           NOT NULL,
    fu_hh_rel_scorres                 SMALLINT,
    fu_sex                            TINYINT,
    fu_hhe_p_live_here                BIT                                   NOT NULL,
    fu_age_scorres                    TINYINT                               NOT NULL,
    fu_marital_scorres                SMALLINT                              NOT NULL,
    fu_hhe_part_available             BIT,
    hhe_fu_hh_count                   TINYINT,
    fu_female_count                   TINYINT,
    fu_m_count_remainder              TINYINT,
    fu_male_count                     TINYINT,
    hhe_fu_female_count               TINYINT,
    hhe_fu_enrolled_arch              SMALLINT,
    hhe_fu_wra_ptid                   VARCHAR(6),
    hhe_fu_dwelling_lsk               SMALLINT,
    dwelling_lsk_yrs                  TINYINT,
    dwelling_lsk_months               TINYINT,
    hhe_fu_reas_lsk_1                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_2                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_3                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_4                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_5                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_6                 BIT                                   NOT NULL,
    hhe_fu_reas_lsk_99                BIT                                   NOT NULL,
    reason_othr                       VARCHAR(32),
    hhe_fu_mig_province               TINYINT,
    hhe_fu_res_out_zm                 VARCHAR(64),
    hhe_fu_hh_ln                      BIT,
    fu_hh_scr                         VARCHAR(30),
    household_enumeration_fu_complete SMALLINT                               NOT NULL,
    created_at                        timestamp default current_timestamp() not null,
    created_by                        tinytext                              null,
    updated_at                        timestamp default current_timestamp() not null on update current_timestamp(),
    updated_by                        tinytext                              null
);
CREATE INDEX hh_fu_enumeration_record_id_idx ON arch_db.hh_fu_enumeration (record_id);
